//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BlocoDLL.BlocoX {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BlocoXSoap", Namespace="http://webservices.sef.sc.gov.br/wsDfeSiv/")]
    public partial class BlocoX : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TransmitirArquivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarProcessamentoArquivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback DownloadArquivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback CancelarArquivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReprocessarArquivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarPendenciasDesenvolvedorPafEcfOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarPendenciasContribuinteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarArquivosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarHistoricoArquivoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarStatusMetodosBlocoXOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public BlocoX() {
            this.Url = global::BlocoDLL.Properties.Settings.Default.BlocoDLL_BlocoX_BlocoX;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TransmitirArquivoCompletedEventHandler TransmitirArquivoCompleted;
        
        /// <remarks/>
        public event ConsultarProcessamentoArquivoCompletedEventHandler ConsultarProcessamentoArquivoCompleted;
        
        /// <remarks/>
        public event DownloadArquivoCompletedEventHandler DownloadArquivoCompleted;
        
        /// <remarks/>
        public event CancelarArquivoCompletedEventHandler CancelarArquivoCompleted;
        
        /// <remarks/>
        public event ReprocessarArquivoCompletedEventHandler ReprocessarArquivoCompleted;
        
        /// <remarks/>
        public event ConsultarPendenciasDesenvolvedorPafEcfCompletedEventHandler ConsultarPendenciasDesenvolvedorPafEcfCompleted;
        
        /// <remarks/>
        public event ConsultarPendenciasContribuinteCompletedEventHandler ConsultarPendenciasContribuinteCompleted;
        
        /// <remarks/>
        public event ListarArquivosCompletedEventHandler ListarArquivosCompleted;
        
        /// <remarks/>
        public event ConsultarHistoricoArquivoCompletedEventHandler ConsultarHistoricoArquivoCompleted;
        
        /// <remarks/>
        public event ConsultarStatusMetodosBlocoXCompletedEventHandler ConsultarStatusMetodosBlocoXCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.sef.sc.gov.br/wsDfeSiv/TransmitirArquivo", RequestNamespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", ResponseNamespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TransmitirArquivo([System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] pXmlCompactado) {
            object[] results = this.Invoke("TransmitirArquivo", new object[] {
                        pXmlCompactado});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TransmitirArquivoAsync(byte[] pXmlCompactado) {
            this.TransmitirArquivoAsync(pXmlCompactado, null);
        }
        
        /// <remarks/>
        public void TransmitirArquivoAsync(byte[] pXmlCompactado, object userState) {
            if ((this.TransmitirArquivoOperationCompleted == null)) {
                this.TransmitirArquivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTransmitirArquivoOperationCompleted);
            }
            this.InvokeAsync("TransmitirArquivo", new object[] {
                        pXmlCompactado}, this.TransmitirArquivoOperationCompleted, userState);
        }
        
        private void OnTransmitirArquivoOperationCompleted(object arg) {
            if ((this.TransmitirArquivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TransmitirArquivoCompleted(this, new TransmitirArquivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.sef.sc.gov.br/wsDfeSiv/ConsultarProcessamentoArquivo", RequestNamespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", ResponseNamespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultarProcessamentoArquivo(string pXml) {
            object[] results = this.Invoke("ConsultarProcessamentoArquivo", new object[] {
                        pXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarProcessamentoArquivoAsync(string pXml) {
            this.ConsultarProcessamentoArquivoAsync(pXml, null);
        }
        
        /// <remarks/>
        public void ConsultarProcessamentoArquivoAsync(string pXml, object userState) {
            if ((this.ConsultarProcessamentoArquivoOperationCompleted == null)) {
                this.ConsultarProcessamentoArquivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarProcessamentoArquivoOperationCompleted);
            }
            this.InvokeAsync("ConsultarProcessamentoArquivo", new object[] {
                        pXml}, this.ConsultarProcessamentoArquivoOperationCompleted, userState);
        }
        
        private void OnConsultarProcessamentoArquivoOperationCompleted(object arg) {
            if ((this.ConsultarProcessamentoArquivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarProcessamentoArquivoCompleted(this, new ConsultarProcessamentoArquivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.sef.sc.gov.br/wsDfeSiv/DownloadArquivo", RequestNamespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", ResponseNamespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string DownloadArquivo(string pXml) {
            object[] results = this.Invoke("DownloadArquivo", new object[] {
                        pXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DownloadArquivoAsync(string pXml) {
            this.DownloadArquivoAsync(pXml, null);
        }
        
        /// <remarks/>
        public void DownloadArquivoAsync(string pXml, object userState) {
            if ((this.DownloadArquivoOperationCompleted == null)) {
                this.DownloadArquivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDownloadArquivoOperationCompleted);
            }
            this.InvokeAsync("DownloadArquivo", new object[] {
                        pXml}, this.DownloadArquivoOperationCompleted, userState);
        }
        
        private void OnDownloadArquivoOperationCompleted(object arg) {
            if ((this.DownloadArquivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DownloadArquivoCompleted(this, new DownloadArquivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.sef.sc.gov.br/wsDfeSiv/CancelarArquivo", RequestNamespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", ResponseNamespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CancelarArquivo(string pXml) {
            object[] results = this.Invoke("CancelarArquivo", new object[] {
                        pXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CancelarArquivoAsync(string pXml) {
            this.CancelarArquivoAsync(pXml, null);
        }
        
        /// <remarks/>
        public void CancelarArquivoAsync(string pXml, object userState) {
            if ((this.CancelarArquivoOperationCompleted == null)) {
                this.CancelarArquivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCancelarArquivoOperationCompleted);
            }
            this.InvokeAsync("CancelarArquivo", new object[] {
                        pXml}, this.CancelarArquivoOperationCompleted, userState);
        }
        
        private void OnCancelarArquivoOperationCompleted(object arg) {
            if ((this.CancelarArquivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CancelarArquivoCompleted(this, new CancelarArquivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.sef.sc.gov.br/wsDfeSiv/ReprocessarArquivo", RequestNamespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", ResponseNamespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ReprocessarArquivo(string pXml) {
            object[] results = this.Invoke("ReprocessarArquivo", new object[] {
                        pXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ReprocessarArquivoAsync(string pXml) {
            this.ReprocessarArquivoAsync(pXml, null);
        }
        
        /// <remarks/>
        public void ReprocessarArquivoAsync(string pXml, object userState) {
            if ((this.ReprocessarArquivoOperationCompleted == null)) {
                this.ReprocessarArquivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReprocessarArquivoOperationCompleted);
            }
            this.InvokeAsync("ReprocessarArquivo", new object[] {
                        pXml}, this.ReprocessarArquivoOperationCompleted, userState);
        }
        
        private void OnReprocessarArquivoOperationCompleted(object arg) {
            if ((this.ReprocessarArquivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReprocessarArquivoCompleted(this, new ReprocessarArquivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.sef.sc.gov.br/wsDfeSiv/ConsultarPendenciasDesenvolvedorPafEcf", RequestNamespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", ResponseNamespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultarPendenciasDesenvolvedorPafEcf(string pXml) {
            object[] results = this.Invoke("ConsultarPendenciasDesenvolvedorPafEcf", new object[] {
                        pXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarPendenciasDesenvolvedorPafEcfAsync(string pXml) {
            this.ConsultarPendenciasDesenvolvedorPafEcfAsync(pXml, null);
        }
        
        /// <remarks/>
        public void ConsultarPendenciasDesenvolvedorPafEcfAsync(string pXml, object userState) {
            if ((this.ConsultarPendenciasDesenvolvedorPafEcfOperationCompleted == null)) {
                this.ConsultarPendenciasDesenvolvedorPafEcfOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarPendenciasDesenvolvedorPafEcfOperationCompleted);
            }
            this.InvokeAsync("ConsultarPendenciasDesenvolvedorPafEcf", new object[] {
                        pXml}, this.ConsultarPendenciasDesenvolvedorPafEcfOperationCompleted, userState);
        }
        
        private void OnConsultarPendenciasDesenvolvedorPafEcfOperationCompleted(object arg) {
            if ((this.ConsultarPendenciasDesenvolvedorPafEcfCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarPendenciasDesenvolvedorPafEcfCompleted(this, new ConsultarPendenciasDesenvolvedorPafEcfCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.sef.sc.gov.br/wsDfeSiv/ConsultarPendenciasContribuinte", RequestNamespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", ResponseNamespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultarPendenciasContribuinte(string pXml) {
            object[] results = this.Invoke("ConsultarPendenciasContribuinte", new object[] {
                        pXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarPendenciasContribuinteAsync(string pXml) {
            this.ConsultarPendenciasContribuinteAsync(pXml, null);
        }
        
        /// <remarks/>
        public void ConsultarPendenciasContribuinteAsync(string pXml, object userState) {
            if ((this.ConsultarPendenciasContribuinteOperationCompleted == null)) {
                this.ConsultarPendenciasContribuinteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarPendenciasContribuinteOperationCompleted);
            }
            this.InvokeAsync("ConsultarPendenciasContribuinte", new object[] {
                        pXml}, this.ConsultarPendenciasContribuinteOperationCompleted, userState);
        }
        
        private void OnConsultarPendenciasContribuinteOperationCompleted(object arg) {
            if ((this.ConsultarPendenciasContribuinteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarPendenciasContribuinteCompleted(this, new ConsultarPendenciasContribuinteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.sef.sc.gov.br/wsDfeSiv/ListarArquivos", RequestNamespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", ResponseNamespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ListarArquivos(string pXml) {
            object[] results = this.Invoke("ListarArquivos", new object[] {
                        pXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ListarArquivosAsync(string pXml) {
            this.ListarArquivosAsync(pXml, null);
        }
        
        /// <remarks/>
        public void ListarArquivosAsync(string pXml, object userState) {
            if ((this.ListarArquivosOperationCompleted == null)) {
                this.ListarArquivosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarArquivosOperationCompleted);
            }
            this.InvokeAsync("ListarArquivos", new object[] {
                        pXml}, this.ListarArquivosOperationCompleted, userState);
        }
        
        private void OnListarArquivosOperationCompleted(object arg) {
            if ((this.ListarArquivosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarArquivosCompleted(this, new ListarArquivosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.sef.sc.gov.br/wsDfeSiv/ConsultarHistoricoArquivo", RequestNamespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", ResponseNamespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultarHistoricoArquivo(string pXml) {
            object[] results = this.Invoke("ConsultarHistoricoArquivo", new object[] {
                        pXml});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarHistoricoArquivoAsync(string pXml) {
            this.ConsultarHistoricoArquivoAsync(pXml, null);
        }
        
        /// <remarks/>
        public void ConsultarHistoricoArquivoAsync(string pXml, object userState) {
            if ((this.ConsultarHistoricoArquivoOperationCompleted == null)) {
                this.ConsultarHistoricoArquivoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarHistoricoArquivoOperationCompleted);
            }
            this.InvokeAsync("ConsultarHistoricoArquivo", new object[] {
                        pXml}, this.ConsultarHistoricoArquivoOperationCompleted, userState);
        }
        
        private void OnConsultarHistoricoArquivoOperationCompleted(object arg) {
            if ((this.ConsultarHistoricoArquivoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarHistoricoArquivoCompleted(this, new ConsultarHistoricoArquivoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.sef.sc.gov.br/wsDfeSiv/ConsultarStatusMetodosBlocoX", RequestNamespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", ResponseNamespace="http://webservices.sef.sc.gov.br/wsDfeSiv/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultarStatusMetodosBlocoX() {
            object[] results = this.Invoke("ConsultarStatusMetodosBlocoX", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarStatusMetodosBlocoXAsync() {
            this.ConsultarStatusMetodosBlocoXAsync(null);
        }
        
        /// <remarks/>
        public void ConsultarStatusMetodosBlocoXAsync(object userState) {
            if ((this.ConsultarStatusMetodosBlocoXOperationCompleted == null)) {
                this.ConsultarStatusMetodosBlocoXOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarStatusMetodosBlocoXOperationCompleted);
            }
            this.InvokeAsync("ConsultarStatusMetodosBlocoX", new object[0], this.ConsultarStatusMetodosBlocoXOperationCompleted, userState);
        }
        
        private void OnConsultarStatusMetodosBlocoXOperationCompleted(object arg) {
            if ((this.ConsultarStatusMetodosBlocoXCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarStatusMetodosBlocoXCompleted(this, new ConsultarStatusMetodosBlocoXCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void TransmitirArquivoCompletedEventHandler(object sender, TransmitirArquivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TransmitirArquivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TransmitirArquivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ConsultarProcessamentoArquivoCompletedEventHandler(object sender, ConsultarProcessamentoArquivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarProcessamentoArquivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarProcessamentoArquivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void DownloadArquivoCompletedEventHandler(object sender, DownloadArquivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DownloadArquivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DownloadArquivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void CancelarArquivoCompletedEventHandler(object sender, CancelarArquivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CancelarArquivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CancelarArquivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ReprocessarArquivoCompletedEventHandler(object sender, ReprocessarArquivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReprocessarArquivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReprocessarArquivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ConsultarPendenciasDesenvolvedorPafEcfCompletedEventHandler(object sender, ConsultarPendenciasDesenvolvedorPafEcfCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarPendenciasDesenvolvedorPafEcfCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarPendenciasDesenvolvedorPafEcfCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ConsultarPendenciasContribuinteCompletedEventHandler(object sender, ConsultarPendenciasContribuinteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarPendenciasContribuinteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarPendenciasContribuinteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ListarArquivosCompletedEventHandler(object sender, ListarArquivosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarArquivosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarArquivosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ConsultarHistoricoArquivoCompletedEventHandler(object sender, ConsultarHistoricoArquivoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarHistoricoArquivoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarHistoricoArquivoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ConsultarStatusMetodosBlocoXCompletedEventHandler(object sender, ConsultarStatusMetodosBlocoXCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarStatusMetodosBlocoXCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarStatusMetodosBlocoXCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591